export const personality = [
    "Loyal",
    "Playful",
    "Cuddly",
    "Curious",
    "Independent",
    "Goofy",
    "Alert",
    "Affectionate",
    "Stubborn",
    "Clever",
    "Energetic",
    "Grumpy",
    "Relaxed",
    "Social",
    "Vocal",
    "Mischievous",
    "Protective",
    "Forgiving",
    "Comforting",
    "Loving",
];

export const Behaviors = [
    "Sniffing",
    "Scratching",
    "Chewing",
    "Hiding",
    "Begging",
    "Digging",
    "Marking",
    "Chasing",
    "Climbing",
    "Purring",
    "Barking",
    "Whining",
    "Meowing",
    "Preening",
    "Sleeping",
    "Stretching",
    "Wagging Tail",
    "Yawning",
    "Panting",
    "Playing Bow",
];

export const catorgry = [
    "Dogs",
    "Cats",
    "Small Animals",
    "Fish",
    "Birds",
    "Reptiles",
    "Exotic Pets",
    "Toads",
    "Horses",
    "Adoption & Rescued",
    "Others",
]